# Info about cluster
cores_per_node: 16     # number of available cores per node 
mem_per_node: 31000    # MB 
project: TG-MCB110022  # a project name (see slurm template)
submission: slurm      # sge to be supported soon
# Installed binaries, absolute paths in remote machine
parsimonator: /your/path/to/parsimonator  
raxmllight: /your/path/to/raxmlLight-AVX
raxmllight_MPI: /your/path/to/raxmlLight-MPI-AVX
raxmllight_pthreads: /your/path/to/raxmlLight-PTHREADS-AVX
raxmlHPC_pthreads: /your/path/to/raxmlHPC-PTHREADS-SSE3
